namespace SASS.Chassis.AI.Token
{
    /// <summary>
    /// This will count token generated by semantic kernel
    /// </summary>
    public interface ITokenCounter
    {
        int CountTokens(string text);
    }
}

